### ISSUE TITLE
Hard way is not that hard

### ISSUE THREAD

**Issue by alright21** [silentsignal/burp-log4shell#1]
Hi! I think that the hard way can be simplified in this way:
1. on issue reported list, CTRL+A to select all the issues, right-click->enabled to disable everything
2. go at the very bottom and select only `Extension generated issue`
That's it! Let me know if it is working for you:)

**Comment by dnet** [comment]
You're right, thanks! (I only tried pressing the spacebar and similar keyboard-based stuff...)

**Comment by alright21** [comment]
No problem, thanks for the plugin! Happy to help

**Comment by Hannah-PortSwigger** [comment]
There should also be an "Audit checks - extensions only" option in your Configuration library.

**Comment by dnet** [comment]
Thanks @Hannah-PortSwigger I modified the README accordingly!
