### ISSUE TITLE
Payloads are not sent with the plugin

### ISSUE THREAD

**Issue by isrtest** [silentsignal/burp-log4shell#15]
## ENV

Burp: v2021.12.1

![log4j-8](https://user-images.githubusercontent.com/76772232/150580190-73c8f62f-1014-47c3-bae5-3152366abef2.png)

```
docker run --name vulnerable-app --rm -p 8000:8080 ghcr.io/christophetd/log4shell-vulnerable-app
```

## Easy Scan
0 Request was sent.

![log4j-1](https://user-images.githubusercontent.com/76772232/150580028-58cafefc-109a-42d3-ab06-7e3ae78abd1c.png)
![log4j-2](https://user-images.githubusercontent.com/76772232/150580030-edb801a5-ed96-4b53-9942-4ab55a977933.png)
![log4j-3](https://user-images.githubusercontent.com/76772232/150580031-8e3ffc14-0278-4b8b-b173-27309297f709.png)
![log4j-4](https://user-images.githubusercontent.com/76772232/150580034-95fa851e-6591-42b1-8fee-430ef4815f2c.png)

## Scan from intruder

2 identical requests were sent. Neither has the payloads.

![log4j-5](https://user-images.githubusercontent.com/76772232/150580035-633de5e7-6069-4554-8c84-70c5d7988424.png)
![log4j-6](https://user-images.githubusercontent.com/76772232/150580037-3ebaba6b-e298-45f4-8146-154401a21739.png)
![log4j-7](https://user-images.githubusercontent.com/76772232/150580041-7aa236c8-4730-4f78-a888-d012b553b878.png)

**Comment by v-p-b** [comment]
Does not conform issue template, closing.

**Comment by isrtest** [comment]
Hi there
I cant find the issue template. The rest of the issues dont seem to follow any pattern.
Did I miss anything? Thanks.

**Comment by v-p-b** [comment]
When you click the New issue button there is a large Bug report box. When you click the Get started button you get a prefilled template with the desired structure.

While at it please do a test with another scanner extension and the extension-only config too so we can see if your problem is specific to this extension or related to your configuration!

**Comment by isrtest** [comment]
**Describe the bug**
Payloads are not sent with the plugin.

**To Reproduce - Easy Scan**
Steps to reproduce the behavior:

1. Start a vul app
    ```
    docker run --name vulnerable-app --rm -p 8000:8080 ghcr.io/christophetd/log4shell-vulnerable-app
    ```
2. Install `Log4Shell Scanner` in BApp Store
3. Import `Extension Only` as per guidance in README
3. Send a request to vul app
4. Right-click on request panel under history tab - Select Scan - Open scan launcher
5. Configuration - Select from Library - Extension Only
6. 0 Request was sent.
7. In Logger tab, no request was found.


**To Reproduce - Initiate scan from Intruder**
Steps to reproduce the behavior:

1. Start a vul app
    ```
    docker run --name vulnerable-app --rm -p 8000:8080 ghcr.io/christophetd/log4shell-vulnerable-app
    ```
2. Install `Log4Shell Scanner` in BApp Store
    
    ![log4j-8](https://user-images.githubusercontent.com/76772232/150580190-73c8f62f-1014-47c3-bae5-3152366abef2.png)

3. Import `Extension Only` as per guidance in README
3. Send a request to vul app
4. Right-click on request panel under history tab - Send to Intruder
5. Add injection points
6. Right click on request panel under Intruder tab - Scan defined insertion point - Open scan launcher
7. Configuration - Select from Library - Extension Only
8. 2 Request was sent.
9. In Logger Tab, 2 requests were found. But neither has the payload.


**Expected behavior**
The scanner should send out requests with payloads in injection points.

**Screenshots**

1. Easy Scan
    ![log4j-1](https://user-images.githubusercontent.com/76772232/150580028-58cafefc-109a-42d3-ab06-7e3ae78abd1c.png)
    ![log4j-2](https://user-images.githubusercontent.com/76772232/150580030-edb801a5-ed96-4b53-9942-4ab55a977933.png)
    ![log4j-3](https://user-images.githubusercontent.com/76772232/150580031-8e3ffc14-0278-4b8b-b173-27309297f709.png)
    ![log4j-4](https://user-images.githubusercontent.com/76772232/150580034-95fa851e-6591-42b1-8fee-430ef4815f2c.png)


2. Initiate Scan from Intruder
    ![log4j-5](https://user-images.githubusercontent.com/76772232/150580035-633de5e7-6069-4554-8c84-70c5d7988424.png)
    ![log4j-6](https://user-images.githubusercontent.com/76772232/150580037-3ebaba6b-e298-45f4-8146-154401a21739.png)
    ![log4j-7](https://user-images.githubusercontent.com/76772232/150580041-7aa236c8-4730-4f78-a888-d012b553b878.png)


**Environment (please complete the following information):**
 - OS: Mac OS 11.6.2
 - Burp version: v2021.12.1

**Additional context**
No issues with [Another Scanner](https://github.com/whwlsfb/Log4j2Scan/)

**Sanity Check**

- [X] I'm not trying to blindly scan random hosts without any configuration and wait for free money from their bug bounty programs.

**Comment by v-p-b** [comment]
Thanks for the proper bug report, repoening!

**Comment by v-p-b** [comment]
So I don't see anything obviously wrong with your setup. The two requests are sent by the Scanner (but not the Extender!) by default. 

I upgraded Burp to 2021.12.1 and couldn't repro the issue either.

Is there anything displayed on the Output and Errors tabs when you select Log4Shell Scanner in Extender?

**Comment by isrtest** [comment]
Hi
I dont see any errors.
https://imgur.com/a/jq7j2Ly

**Comment by v-p-b** [comment]
The Output and Errors tabs are not visible on either of the screenshots unfortunately, you should at least see a "Log4Shell scanner loaded" message in the Output.

Do you use the extension version from the BApp store?

Please select a request, where standard GET parameters are included (`/?=nino` does not contain a parameter name, `/?foo=nino` is better) and use the "Do Active Scan" option from the right click menu so a default scan configuration will run, then verify in Logger if any payloads containing the "jndi" string are sent out!

**Comment by isrtest** [comment]
It turned out I have burp collaborator disabled in `Project Options`. After enabling it, I could now see the requests with payloads.

Currently, the plugin doesnt identify `X-Api-Version` as an injection point. 

If I may, can i suggest updating the README with additional troubleshooting guidance?
1. After loading the plugin, check if any errors in plugin tab. `Extender` - `Burp Extension` - `Log4jShell Scanner` - Error Tab.
2. Ensure Burp Collaborator server option is on. `Project Options` - `Misc` - `Burp Collaborator Server`
3. After a quick scan, visit logger tab to see if every injection point is scanned. If not, try to define the missing injection point, and launch the scan in Intruder Tab - `Scan defined injection points`

**Comment by v-p-b** [comment]
Glad this got resolved! We will definitely consider adding a troubleshooting section somewhere, as this is not the first similar error we have to deal with!

As for detecting insertion points: this is done by Burp, and is beyond the control of simple scanner extensions, but can be controlled by insertion point providers, see: https://github.com/silentsignal/burp-log4shell/issues/3#issuecomment-993575116 .
