### ISSUE TITLE
BApps: Log4Shell scanner

### ISSUE THREAD

**Issue by shreyasmrs** [silentsignal/burp-log4shell#17]
Hi,

Any reason why the Log4Shell scanner is removed from the bApps extensions?

**Comment by dnet** [comment]
Thanks for bringing this to my attention, now that I searched for it, I found an e-mail the PortSwigger team sent me back in January that seemed to have "fallen through the cracks"

> We've been having issues with your extension, Log4Shell Scanner, triggering antivirus software on various platforms.
> 
> Due to this, we are temporarily removing your extension from the BApp Store.
> 
> I believe this occurs due to the Log4Shell payload contained in the extension. If you were to encrypt/encode this and decrypt/decode as necessary, then that may provide a workaround to bypass the antivirus.
> 
> We've had a similar issue occur with "Freddy, Deserialization Bug Finder", so you could take a look at how the author resolved the issue here: https://github.com/PortSwigger/freddy-deserialization-bug-finder
> 
> If you have any questions, please let us know.
> 
> Once this is resolved, please let us know and we can reinstate your extension to the BApp Store.

I'll deal with this shortly...

**Comment by dnet** [comment]
I released v0.2.4 that contains an obfuscated version of the easy-to-fingerprint JNDI prefix, I [opened a PR](https://github.com/PortSwigger/log4shell-scanner/pull/4) and sent a reply to PortSwigger, let's hope for the best...

**Comment by dnet** [comment]
PortSwigger replied

> Thanks for popping those changes in. We'll get the new version built, tested, and hopefully published.
>
> We'll let you know once it's been released, or if we encounter any issues.

**Comment by shreyasmrs** [comment]
thank you for the quick workaround

**Comment by dnet** [comment]
It's been reinstated since 5th October: https://portswigger.net/bappstore/b011be53649346dd87276bca41ce8e8f

Thanks again for reminding me by opening this issue!
