### ISSUE TITLE
Protobuf version error

### ISSUE THREAD

**Issue by ErwinGeirnaert** [silentsignal/burp-log4shell#2]
Hi,

To be able to build this I have to change the protobuf version in build.gradle to be:
    classpath "gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.18"

**Comment by dnet** [comment]
Thanks for the report, this was for another project of ours, Piper, and Protobuf is not really needed for this. :) At least it made the binary a bit smaller.
