### ISSUE TITLE
Running burp-log4shell.jar

### ISSUE THREAD

**Issue by dandrei** [silentsignal/burp-log4shell#5]
Hello,

It's been a while since I've executed `.jar` files, I was under the impression that the command is `java -jar`, yet I get the following:

    java -jar burp-log4shell.jar
    no main manifest attribute, in burp-log4shell.jar

Environment:

    java --version
    openjdk 11.0.13 2021-10-19
    OpenJDK Runtime Environment 18.9 (build 11.0.13+8)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode)

**Comment by fgeek** [comment]
It's a Burp plugin.

**Comment by dandrei** [comment]
Ok, thanks, sorry, I thought it was a standalone tool. Downloading Burp now.
