### ISSUE TITLE
Out of box Burp with single extension not discover Log4shell

### ISSUE THREAD

**Issue by pawel16151** [silentsignal/burp-log4shell#6]
Hi! I've just installed burp pro out of box and the only extension I have added is yours. Unfortunately I am not able to discover any trails of log4shell even I have identified few of such that should be reported based on release notes etc.. Are there any extra plugins/settings that should be enabled/installed to make it scan successfully? Also - should the scan be started from the "/" URL of the target ? 
Thanks !
![Screenshot from 2021-12-14 11-25-48](https://user-images.githubusercontent.com/64260538/145989982-1f2cb977-d8b1-42c3-905e-b19dec573431.png)

![Screenshot from 2021-12-14 11-25-34](https://user-images.githubusercontent.com/64260538/145989994-215ec435-7e2c-48b5-a8da-4803b14abd43.png)

**Comment by Teicu** [comment]
I can confirm this, I've tested about 70 sites in the last few hours and found absolutely nothing

**Comment by v-p-b** [comment]
You can't find Log4shell by randomly scan sites on the internet (well maybe you can, but you should give more thought about what you're doing for sure). The scanner must be able to find an insertion point in your base request, that is vulnerable, so it can insert the payload there (see: https://github.com/silentsignal/burp-log4shell/issues/4#issuecomment-992967941 ). 

If you are absolutely sure, that you are targeting a request that contains a vulnerable parameter, yet the plugin doesn't detect the vuln, feel free to reopen the issue with the supposedly vulnerable request, and a pcap of the traffic.
