### ISSUE TITLE
[Feature] Add context menu option to only scan for log4j

### ISSUE THREAD

**Issue by Regala** [silentsignal/burp-log4shell#9]
Hi folks,

while the method you described to only scan for log4j is viable there is an easier way to do it in Burp, via adding a context menu option. It should go something like:

```
scanMenu = JMenuItem("Log4j scan")
scanMenu.addActionListener(startScan(self))

self.menu = JPopupMenu("Popup")
self.menu.add(scanMenu)

callbacks.registerContextMenuFactory(self)

```

where `startScan` is something like:

```
class sendRequestRepeater(ActionListener):
    def __init__(self, extender):
        self._extender = extender

    def actionPerformed(self, e):

  
            self._extender.doActiveScan(...);

        return 

```

I know this in Python but you get the idea; there are many extensions that hook into `registerContextMenuFactory` so you can just copy from there. Let me know if I can help, cheers :)

Fisher

**Comment by dnet** [comment]
I'm sorry but given the current set of APIs available for Extender plugins, that's just plain impossible. Your code snippets hide the problematic part as `...` in `self._extender.doActiveScan(...);` as [`IScannerCheck.doActivescan`](https://portswigger.net/burp/extender/api/burp/IScannerCheck.html#doActiveScan(burp.IHttpRequestResponse,%20burp.IScannerInsertionPoint)) expects (and in most cases, including this plugin as well, uses) a second parameter with an insertion point (an object that implements [`IScannerInsertionPoint`](https://portswigger.net/burp/extender/api/burp/IScannerInsertionPoint.html)).

So first of all, `doActiveScan` is called not just for a single scan, but once for each insertion point. And there's just no API provided to actually get all those insertion points by an Extender plugin. Try searching for `IScannerInsertionPoint` in the Burp Extender API documentation and you'll find that your average plugin can only interact with such objects in three cases.

 - You get one if you're a scanner check, just as I described above. This is how Active scan works, they call you, never the other way around.
 - You provide such insertion points to the active scanner and it calls all the other scanner checks with those provided by you included in the set. Again, the data flow is unidirectional, you don't get to ask Burp to collect and provide those insertion points for you.
 - You create one manually with `makeScannerInsertionPoint`, however, you have to figure out how to parse its location and what encoding to use. Even the official API documentation states

> It can be used to quickly create a simple insertion point based on a fixed payload location within a base request.

So AFAIK what you ask for is impossible, or to put it in another way, making it possible is just not worth it. You'd have to implement half of the built-in active scanner to implement the code that's already there, it's just inaccessible to your average extension. Another, contrived way would be doing such a version where the user has to select the part manually (like in Intruder) and specify encoding explicitly.

Please only reopen this if you have information that disproves any of the above. If you'd like to do the reimplementation part, feel free to submit a PR.

**Comment by Regala** [comment]
I have my doubts that all extensions that provide a context menu to
initiate an active scan on the current request have done something
impossible but, eh. Cheers

**Comment by dnet** [comment]
Just show me a single one that provides such an option that initiates an active scan on the current request focusing on the single vulnerability class targeted by the extension.
